services:
  - type: web
    name: project-mgt-dashboard
    runtime: php
    plan: free

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force

    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: project_mgt_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: project_mgt_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: project_mgt_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: project_mgt_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: project_mgt_db
          property: password

databases:
  - name: project_mgt_db
   - type: postgresql
   - plan: free

